//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dijingzhizuo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DIJINGZHIZUO_DIALOG         102
#define IDD_OPERENV                     103
#define IDD_RUNWAYPROP                  104
#define IDD_LATLON                      105
#define IDD_PROGRESSDIALOG              106
#define IDD_GENERALAPT                  107
#define IDD_MYDIALOG                    108
#define IDR_HTML_MANAGEPROFILE          109
#define IDR_MAINFRAME                   128
#define IDB_BITMAP2                     139
#define IDB_BITMAP9                     154
#define IDB_BITMAP10                    155
#define IDB_BITMAP11                    156
#define IDB_BITMAP12                    157
#define IDB_BITMAP13                    158
#define IDB_BITMAP14                    159
#define IDB_BITMAP15                    161
#define IDB_BITMAP16                    162
#define IDB_BITMAP1                     166
#define IDI_Cancel                      167
#define IDI_Open                        168
#define IDI_Go                          169
#define IDI_ok                          170
#define IDI_Close                       171
#define IDB_BITMAP3                     172
#define IDB_BITMAP4                     173
#define IDD_DIALOG1                     174
#define IDD_3DBUILD                     175
#define IDB_BITMAP8                     176
#define IDB_BITMAP17                    177
#define IDD_DIALOG2                     178
#define IDD_PROFILE                     178
#define IDB_BITMAP5                     179
#define IDB_BITMAP6                     180
#define IDR_ACCELERATOR1                181
#define IDC_TAB1                        1000
#define IDC_EDIT1                       1002
#define IDC_EDIT_LOD                    1002
#define IDC_BUTTON1                     1003
#define IDC_EDIT2                       1004
#define IDC_LongitudeMAX                1004
#define IDC_BUTTON2                     1005
#define IDC_EDIT3                       1006
#define IDC_LongitudeMIN                1006
#define IDC_BUTTON3                     1007
#define IDC_ivePathName_BUTTON          1007
#define IDC_COMBO1                      1008
#define IDC_COMBO2                      1009
#define IDC_EDIT4                       1010
#define IDC_LatitudeMAX                 1010
#define IDC_EDIT5                       1011
#define IDC_LatitudeMIN                 1011
#define IDC_BUTTON4                     1012
#define IDC_COMBO4                      1012
#define IDC_shBuildingPosition          1012
#define IDC_PiLiang_Button              1012
#define IDC_BUTTON5                     1013
#define IDC_COMBO5                      1013
#define IDC_shBuildingTypes             1013
#define IDC_BUTTON6                     1014
#define IDC_COMBO6                      1014
#define IDC_shAppLightTypes             1014
#define IDC_COMBO3                      1015
#define IDC_COMBO7                      1015
#define IDC_GlideslopeLight2_COMB       1015
#define IDC_shRunwayCondition           1015
#define IDC_BUTTON7                     1016
#define IDC_EDIT6                       1017
#define IDC_fVLAAngles                  1017
#define IDC_EDIT7                       1018
#define IDC_fRunwaySlope                1018
#define IDC_EDIT8                       1019
#define IDC_cICAO                       1019
#define IDC_EDIT9                       1020
#define IDC_cLocation                   1020
#define IDC_COMBO8                      1021
#define IDC_shVLATypes                  1021
#define IDC_COMBO9                      1022
#define IDC_COMBO10                     1023
#define IDC_Should_COMB                 1023
#define IDC_EDIT10                      1024
#define IDC_CHECK1                      1025
#define IDC_EDIT11                      1028
#define IDC_LIST1                       1030
#define IDC_LIST2                       1034
#define IDC_STATIC_1                    1035
#define IDC_STATIC_5                    1036
#define IDC_STATIC_2                    1037
#define IDC_STATIC_4                    1038
#define IDC_DEMPathName_BUTTON          1039
#define IDC_STATIC_6                    1039
#define IDC_TexPathName_BUTTON          1040
#define IDC_TexPathName_EDIT            1042
#define IDC_DEMPathName_EDIT            1043
#define IDC_ivePathName_EDIT            1044
#define IDC_lon_EDIT                    1045
#define IDC_lat_EDIT                    1046
#define IDC_LonRage_EDIT                1047
#define IDC_LatRage_EDIT                1048
#define IDC_DateSum_EDIT                1049
#define IDC_Scalse_EDIT                 1050
#define IDC_Lenght_EDIT                 1051
#define IDC_Width_EDIT                  1052
#define IDC_Heading_EDIT                1053
#define IDC_Longitude_EDIT              1054
#define IDC_Latitude_EDIT               1055
#define IDC_DispThr1_EDIT               1056
#define IDC_DispThr2_EDIT               1057
#define IDC_Stopway1_EDIT               1058
#define IDC_Stopway2_EDIT               1059
#define IDC_RunwayLight1_COMB           1060
#define IDC_RunwayLight2_COMB           1061
#define IDC_ApproachLight1_COMB         1062
#define IDC_ApproachLight2_COMB         1063
#define IDC_GlideslopeLight1_COMB       1064
#define IDC_SurfaceType_COMB            1065
#define IDC_RunwayAlt_EDIT              1066
#define IDC_OK                          1067
#define IDC_cancel                      1068
#define IDC_shRunwayID                  1069
#define IDC_dLatitude                   1070
#define IDC_dLongtitude                 1071
#define IDC_fAltitude                   1072
#define IDC_fHeading                    1073
#define IDC_shRunwayWidth               1074
#define IDC_shRunwayLength              1075
#define IDC_AnXu_Button                 1076
#define IDC_PROFILE                     1077
#define IDC_EDIT                        1077
#define IDC_TREE1                       1078
#define IDC_SAVE                        1079
#define IDC_REFRESH                     1080
#define IDC_RESET_TERRAIN               1081
#define IDC_DELETE                      1082
#define IDC_CHECK_AIRPORT               1082
#define IDC_Batch_Button                1083
#define IDC_STATIC1                     1083
#define IDC_STATIC2                     1084
#define IDC_STATIC5                     1085
#define IDC_STATIC3                     1086
#define IDC_STATIC6                     1087
#define IDC_STATIC4                     1088
#define IDC_STATIC7                     1089
#define IDC_STATIC8                     1090
#define IDC_STATIC9                     1091
#define IDC_ROADWIDE                    1092
#define IDC_LIGHTDISTANCE               1093
#define IDC_CHECK_LAMP                  1094
#define IDC_STATIC13                    1095
#define IDC_ROADWIDE2                   1096
#define IDC_WOODCOVERAGE                1096
#define IDC_TREE_TERRAIN                1096
#define IDC_REFRESH_TERRAIN             1097
#define IDC_LIST_TERRAIN                1098
#define IDC_TREE_CULTURE                1099
#define IDC_REFRESH_CULTURE             1100
#define IDC_RESET_CULTURE               1101
#define IDC_CREATE_BUTTON               1102
#define IDC_LIST_CULTRUE                1103
#define IDC_LIST_CULTURE                1103
#define ID_ACCELERATOR1                 32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
